// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pb/kama.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KamaCache_Get_FullMethodName      = "/pb.KamaCache/Get"
	KamaCache_GetLocal_FullMethodName = "/pb.KamaCache/GetLocal"
	KamaCache_Set_FullMethodName      = "/pb.KamaCache/Set"
	KamaCache_SetLocal_FullMethodName = "/pb.KamaCache/SetLocal"
	KamaCache_Delete_FullMethodName   = "/pb.KamaCache/Delete"
)

// KamaCacheClient is the client API for KamaCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KamaCacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	GetLocal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	SetLocal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error)
}

type kamaCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewKamaCacheClient(cc grpc.ClientConnInterface) KamaCacheClient {
	return &kamaCacheClient{cc}
}

func (c *kamaCacheClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, KamaCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaCacheClient) GetLocal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, KamaCache_GetLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaCacheClient) Set(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, KamaCache_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaCacheClient) SetLocal(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, KamaCache_SetLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaCacheClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForDelete)
	err := c.cc.Invoke(ctx, KamaCache_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KamaCacheServer is the server API for KamaCache service.
// All implementations must embed UnimplementedKamaCacheServer
// for forward compatibility.
type KamaCacheServer interface {
	Get(context.Context, *Request) (*ResponseForGet, error)
	GetLocal(context.Context, *Request) (*ResponseForGet, error)
	Set(context.Context, *Request) (*ResponseForGet, error)
	SetLocal(context.Context, *Request) (*ResponseForGet, error)
	Delete(context.Context, *Request) (*ResponseForDelete, error)
	mustEmbedUnimplementedKamaCacheServer()
}

// UnimplementedKamaCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKamaCacheServer struct{}

func (UnimplementedKamaCacheServer) Get(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKamaCacheServer) GetLocal(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocal not implemented")
}
func (UnimplementedKamaCacheServer) Set(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedKamaCacheServer) SetLocal(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLocal not implemented")
}
func (UnimplementedKamaCacheServer) Delete(context.Context, *Request) (*ResponseForDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKamaCacheServer) mustEmbedUnimplementedKamaCacheServer() {}
func (UnimplementedKamaCacheServer) testEmbeddedByValue()                   {}

// UnsafeKamaCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KamaCacheServer will
// result in compilation errors.
type UnsafeKamaCacheServer interface {
	mustEmbedUnimplementedKamaCacheServer()
}

func RegisterKamaCacheServer(s grpc.ServiceRegistrar, srv KamaCacheServer) {
	// If the following call pancis, it indicates UnimplementedKamaCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KamaCache_ServiceDesc, srv)
}

func _KamaCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaCache_GetLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaCacheServer).GetLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaCache_GetLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaCacheServer).GetLocal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaCache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaCacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaCache_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaCacheServer).Set(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaCache_SetLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaCacheServer).SetLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaCache_SetLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaCacheServer).SetLocal(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaCache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaCache_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaCacheServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// KamaCache_ServiceDesc is the grpc.ServiceDesc for KamaCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KamaCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KamaCache",
	HandlerType: (*KamaCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KamaCache_Get_Handler,
		},
		{
			MethodName: "GetLocal",
			Handler:    _KamaCache_GetLocal_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KamaCache_Set_Handler,
		},
		{
			MethodName: "SetLocal",
			Handler:    _KamaCache_SetLocal_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KamaCache_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/kama.proto",
}
